const inv = [
  { author_id: 1, author_name: "Alice Bennett", listed_price: 19.99 },
  { author_id: 2, author_name: "Brian Maxwell", listed_price: 25.5 },
  { author_id: 3, author_name: "Carla Jennings", listed_price: 14.0 },
  { author_id: 4, author_name: "Daniel Carter", listed_price: 21.75 },
  { author_id: 5, author_name: "Emily Watson", listed_price: 17.3 },
  { author_id: 6, author_name: "Felix Hart", listed_price: 12.99 },
  { author_id: 7, author_name: "Georgia Lee", listed_price: 18.2 },
  { author_id: 8, author_name: "Harold Stone", listed_price: 29.99 },
  { author_id: 9, author_name: "Ivy Raymond", listed_price: 24.0 },
  { author_id: 10, author_name: "James Nolan", listed_price: 15.49 },
  { author_id: 11, author_name: "Kara Simmons", listed_price: 19.95 },
  { author_id: 12, author_name: "Liam Morgan", listed_price: 22.1 },
  { author_id: 13, author_name: "Mia Collins", listed_price: 16.8 },
  { author_id: 14, author_name: "Nathan Blake", listed_price: 20.0 },
  { author_id: 15, author_name: "Olivia Rhodes", listed_price: 26.25 },
  { author_id: 16, author_name: "Peter Lawson", listed_price: 13.99 },
  { author_id: 17, author_name: "Quinn Davis", listed_price: 23.0 },
  { author_id: 18, author_name: "Rachel Ford", listed_price: 19.25 },
  { author_id: 19, author_name: "Samuel Grant", listed_price: 21.99 },
  { author_id: 20, author_name: "Tina Moore", listed_price: 27.49 },
  { author_id: 21, author_name: "Umar Franklin", listed_price: 16.75 },
  { author_id: 22, author_name: "Vera Hughes", listed_price: 18.9 },
  { author_id: 23, author_name: "Wesley Brooks", listed_price: 24.95 },
  { author_id: 24, author_name: "Xena Russell", listed_price: 20.8 },
  { author_id: 25, author_name: "Yara Benson", listed_price: 22.45 },
  { author_id: 26, author_name: "Zachary Payne", listed_price: 28.6 },
  { author_id: 27, author_name: "Aaron Schultz", listed_price: 17.9 },
  { author_id: 28, author_name: "Bianca Clarke", listed_price: 14.75 },
  { author_id: 29, author_name: "Colton Hayes", listed_price: 19.1 },
  { author_id: 30, author_name: "Daisy Wheeler", listed_price: 26.99 },
];

export default inv;
